name: build-and-push-docker

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*', 'v*.*', 'v*' ]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,format=short
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL || vars.VITE_API_URL || '' }}
            HTTP_PROXY=${{ secrets.BUILD_HTTP_PROXY || vars.BUILD_HTTP_PROXY || '' }}
            HTTPS_PROXY=${{ secrets.BUILD_HTTPS_PROXY || vars.BUILD_HTTPS_PROXY || '' }}
            ALL_PROXY=${{ secrets.BUILD_ALL_PROXY || vars.BUILD_ALL_PROXY || '' }}
            NO_PROXY=${{ secrets.BUILD_NO_PROXY || vars.BUILD_NO_PROXY || '' }}

# Notes:
# - 默认推送到 GHCR，镜像名为 ghcr.io/<owner>/<repo>:<tag>
# - 若要推送到 Docker Hub，可添加一个额外的 login 步骤与 images 设置，例如：
#   - uses: docker/login-action@v3
#     with:
#       username: ${{ secrets.DOCKERHUB_USERNAME }}
#       password: ${{ secrets.DOCKERHUB_TOKEN }}
#   并在 docker/metadata-action 的 images 加上一行 docker.io/<namespace>/<repo>
